on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }}-sqlite-${{ matrix.os }}

    env:
      COMPOSER_ROOT_VERSION: dev-master
      EXTENSIONS: pdo, pdo_sqlite

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5

        exclude:
          - os: windows-latest
            php: 8.2

          - os: windows-latest
            php: 8.3

          - os: windows-latest
            php: 8.4

    steps:
      - name: Checkout.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f

      - name: Run tests with phpunit with code coverage.
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --colors=always

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
