<?php

declare(strict_types=1);

use Cycle\ORM\Schema;
use Cycle\ORM\Relation;
use Cycle\Schema\Relation\RelationSchema;

return [
    'token' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'token',
        Schema::ENTITY => 'App\\Token\\Manager\\Entity\\Token',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'App\\Token\\Manager\\TokenRepository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'token' => 'token',
            'relation_id' => 'relation_id',
            'role' => 'role',
            'expire_at' => 'expire_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'expire_at' => 'datetime',
        ],
        Schema::RELATIONS => [],
    ],
    'userAgency' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'user_agency',
        Schema::ENTITY => 'App\\User\\Entity\\UserAgency',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'user_id' => 'user_id',
            'agency_id' => 'agency_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'user_id' => 'int',
            'agency_id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'user' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'user',
        Schema::ENTITY => 'App\\User\\Entity\\User',
        Schema::MAPPER => 'App\\User\\Mapper\\UserMapper',
        Schema::REPOSITORY => 'App\\User\\UserRepository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'email' => 'email',
            'password' => 'password',
            'status' => 'status',
            'createdAt' => 'create_time',
            'updatedAt' => 'update_time',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'status' => ['App\\User\\Typecast\\UserStatus', 'typecast'],
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
        ],
        Schema::RELATIONS => [
            'agencies' => [
                Relation::TYPE => Relation::MANY_TO_MANY,
                Relation::TARGET => 'agency',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::ORDER_BY => [
                        'id' => 'DESC',
                    ],
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'id',
                    Relation::THROUGH_ENTITY => 'userAgency',
                    Relation::THROUGH_INNER_KEY => 'user_id',
                    Relation::THROUGH_OUTER_KEY => 'agency_id',
                    Relation::THROUGH_WHERE => [],
                ],
            ],
        ],
    ],
    'agency' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'agency',
        Schema::ENTITY => 'App\\Agency\\Entity\\Agency',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'name' => 'name',
            'shortName' => 'short_name',
            'description' => 'description',
            'status' => 'status',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'user_id' => 'user_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'status' => ['App\\Agency\\Enum\\AgencyStatus', 'typecast'],
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'user_id' => 'int',
        ],
        Schema::RELATIONS => [
            'user' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'user',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'user_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'translate' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_translate',
        Schema::ENTITY => 'App\\Iata\\Entity\\Translate',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'relation_id' => 'relation_id',
            'relation_role' => 'relation_role',
            'name' => 'name',
            'language' => 'language',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'relation_id' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [],
    ],
    'country' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_country',
        Schema::ENTITY => 'App\\Iata\\Entity\\Country',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'continent_id' => 'continent_id',
            'numericIso' => 'numeric_iso',
            'iso' => 'iso',
            'iso3' => 'iso3',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'continent_id' => 'int',
            'numericIso' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'continent' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'continent',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'continent_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
        ],
    ],
    'city' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_city',
        Schema::ENTITY => 'App\\Iata\\Entity\\City',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'country_id' => 'country_id',
            'iata' => 'iata',
            'latitude' => 'latitude',
            'longitude' => 'longitude',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'country_id' => 'int',
            'latitude' => 'float',
            'longitude' => 'float',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
            'country' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'country',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'country_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'airport' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_airport',
        Schema::ENTITY => 'App\\Iata\\Entity\\Airport',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'city_id' => 'city_id',
            'iata' => 'iata',
            'latitude' => 'latitude',
            'longitude' => 'longitude',
            'status' => 'status',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'city_id' => 'int',
            'latitude' => 'float',
            'longitude' => 'float',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
            'city' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'city',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'city_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'railStation' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_rail_station',
        Schema::ENTITY => 'App\\Iata\\Entity\\RailStation',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'city_id' => 'city_id',
            'iata' => 'iata',
            'latitude' => 'latitude',
            'longitude' => 'longitude',
            'status' => 'status',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'city_id' => 'int',
            'latitude' => 'float',
            'longitude' => 'float',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
            'city' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'city',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'city_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'carrier' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_carrier',
        Schema::ENTITY => 'App\\Iata\\Entity\\Carrier',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'iata' => 'iata',
            'type' => 'type',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
        ],
    ],
    'continent' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'iata_continent',
        Schema::ENTITY => 'App\\Iata\\Entity\\Continent',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'code' => 'code',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ],
        Schema::RELATIONS => [
            'translations' => [
                Relation::TYPE => Relation::MORPHED_HAS_MANY,
                Relation::TARGET => 'translate',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => true,
                    Relation::OUTER_KEY => 'relation_id',
                    Relation::INNER_KEY => 'id',
                    Relation::MORPH_KEY => 'relation_role',
                    RelationSchema::MORPH_KEY_LENGTH => 32,
                ],
            ],
        ],
    ],
    'price' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_price',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Price',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'amount' => 'amount',
            'currency' => 'currency',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'offer_id' => 'offer_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'offer_id' => 'int',
        ],
        Schema::RELATIONS => [
            'offer' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'offer',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'offer_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
            'fare' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'price:fare',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
            'fee' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'price:fee',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
        ],
    ],
    'offer' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Offer',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'search_id' => 'search_id',
            'booking_id' => 'booking_id',
            'provider_id' => 'provider_id',
            'airline_type' => 'airline_type',
            'hash' => 'hash',
            'operating_carrier' => 'operating_carrier',
            'baggage_recheck_required' => 'baggage_recheck_required',
            'has_airport_change' => 'has_airport_change',
            'stopovers' => 'stopovers',
            'night_in_destination' => 'night_in_destination',
            'journey_time' => 'journey_time',
            'virtual_interlining' => 'virtual_interlining',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'booking_relation_id' => 'booking_relation_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'baggage_recheck_required' => 'bool',
            'has_airport_change' => 'bool',
            'stopovers' => 'int',
            'night_in_destination' => 'int',
            'journey_time' => 'int',
            'virtual_interlining' => 'bool',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'booking_relation_id' => 'int',
        ],
        Schema::RELATIONS => [
            'booking' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'booking',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'booking_relation_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
            'parts' => [
                Relation::TYPE => Relation::HAS_MANY,
                Relation::TARGET => 'part',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::ORDER_BY => [],
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'offer_id',
                ],
            ],
            'price' => [
                Relation::TYPE => Relation::HAS_ONE,
                Relation::TARGET => 'price',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'offer_id',
                ],
            ],
        ],
    ],
    'bookingPerson' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_person',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\BookingPerson',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'name' => 'name',
            'email' => 'email',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'booking_id' => 'booking_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'booking_id' => 'int',
        ],
        Schema::RELATIONS => [
            'booking' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'booking',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'booking_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'part' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Part',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'type' => 'type',
            'journey_time' => 'journey_time',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'offer_id' => 'offer_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'journey_time' => 'int',
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'offer_id' => 'int',
        ],
        Schema::RELATIONS => [
            'badges' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'part:badges',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
            'segments' => [
                Relation::TYPE => Relation::HAS_MANY,
                Relation::TARGET => 'segment',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'part_id',
                ],
            ],
            'offer' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'offer',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'offer_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'booking' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Booking',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'booking_id' => 'booking_id',
            'pnr_number' => 'pnr_number',
            'ticketing_expiry_date' => 'ticketing_expiry_date',
            'status' => 'status',
            'checkinStatus' => 'checkin_status',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'agency_id' => 'agency_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'ticketing_expiry_date' => 'datetime',
            'status' => ['App\\Flight\\Booking\\Enum\\BookingStatus', 'typecast'],
            'checkinStatus' => ['App\\Flight\\Booking\\Enum\\CheckInStatus', 'typecast'],
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'agency_id' => 'int',
        ],
        Schema::RELATIONS => [
            'booking_person' => [
                Relation::TYPE => Relation::HAS_ONE,
                Relation::TARGET => 'bookingPerson',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'booking_id',
                ],
            ],
            'agency' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'agency',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'agency_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
            'offer' => [
                Relation::TYPE => Relation::HAS_ONE,
                Relation::TARGET => 'offer',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'booking_relation_id',
                ],
            ],
            'passengers' => [
                Relation::TYPE => Relation::HAS_MANY,
                Relation::TARGET => 'passenger',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::WHERE => [],
                    Relation::INNER_KEY => 'id',
                    Relation::OUTER_KEY => 'booking_id',
                ],
            ],
        ],
    ],
    'segment' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part_segment',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Segment',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'from' => 'from',
            'to' => 'to',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'part_id' => 'part_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'from' => ['App\\Flight\\Booking\\Typecast\\CodeTypecast', 'typecast'],
            'to' => ['App\\Flight\\Booking\\Typecast\\CodeTypecast', 'typecast'],
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'part_id' => 'int',
        ],
        Schema::RELATIONS => [
            'part' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'part',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'part_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
            'flight' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'segment:flight',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
            'terminal' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'segment:terminal',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
            'date' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'segment:date',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
            'properties' => [
                Relation::TYPE => 1,
                Relation::TARGET => 'segment:properties',
                Relation::LOAD => Relation::LOAD_EAGER,
                Relation::SCHEMA => [],
            ],
        ],
    ],
    'passenger' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_passenger',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Passenger',
        Schema::MAPPER => 'Yiisoft\\Yii\\Cycle\\Mapper\\TimestampedMapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'id' => 'id',
            'type' => 'type',
            'fields' => 'fields',
            'createdAt' => 'created_at',
            'updatedAt' => 'updated_at',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'booking_id' => 'booking_id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
            'type' => ['Flight\\Data\\Provider\\Booking\\Enum\\PassengerType', 'typecast'],
            'fields' => ['Flight\\Data\\Provider\\Booking\\Injection\\PassengerFields', 'typecast'],
            'createdAt' => 'datetime',
            'updatedAt' => 'datetime',
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'booking_id' => 'int',
        ],
        Schema::RELATIONS => [
            'booking' => [
                Relation::TYPE => Relation::BELONGS_TO,
                Relation::TARGET => 'booking',
                Relation::LOAD => Relation::LOAD_PROMISE,
                Relation::SCHEMA => [
                    Relation::CASCADE => true,
                    Relation::NULLABLE => false,
                    Relation::INNER_KEY => 'booking_id',
                    Relation::OUTER_KEY => 'id',
                ],
            ],
        ],
    ],
    'price:fare' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_price',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Fare',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'adults_amount' => 'fare_adults_amount',
            'adults_currency' => 'fare_adults_currency',
            'children_amount' => 'fare_children_amount',
            'children_currency' => 'fare_children_currency',
            'infants_amount' => 'fare_infants_amount',
            'infants_currency' => 'fare_infants_currency',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'price:fee' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_price',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Fee',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'adults_amount' => 'fee_adults_amount',
            'adults_currency' => 'fee_adults_currency',
            'children_amount' => 'fee_children_amount',
            'children_currency' => 'fee_children_currency',
            'infants_amount' => 'fee_infants_amount',
            'infants_currency' => 'fee_infants_currency',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'part:badges' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Badges',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'night' => 'badge_night',
            'train' => 'badge_train',
            'change_airport' => 'badge_change_airport',
            'recheck_baggage' => 'badge_recheck_baggage',
            'no_luggage' => 'badge_no_luggage',
            'smart_connection' => 'badge_smart_connection',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'night' => 'bool',
            'train' => 'bool',
            'change_airport' => 'bool',
            'recheck_baggage' => 'bool',
            'no_luggage' => 'bool',
            'smart_connection' => 'bool',
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'segment:flight' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part_segment',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Segment\\Flight',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'number' => 'flight_number',
            'duration' => 'flight_duration',
            'carrier' => 'flight_carrier',
            'plane' => 'flight_plane',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'duration' => 'int',
            'carrier' => ['App\\Flight\\Booking\\Typecast\\CodeTypecast', 'typecast'],
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'segment:terminal' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part_segment',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Segment\\Terminal',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'departure' => 'terminal_departure',
            'arrival' => 'terminal_arrival',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'segment:date' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part_segment',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Segment\\Date',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'departure' => 'date_departure',
            'arrival' => 'date_arrival',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'departure' => 'datetime',
            'arrival' => 'datetime',
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
    'segment:properties' => [
        Schema::DATABASE => 'default',
        Schema::TABLE => 'booking_offer_part_segment',
        Schema::ENTITY => 'App\\Flight\\Booking\\Entity\\Embedded\\Segment\\Properties',
        Schema::MAPPER => 'Cycle\\ORM\\Mapper\\Mapper',
        Schema::REPOSITORY => 'Cycle\\ORM\\Select\\Repository',
        Schema::CONSTRAIN => null,
        Schema::PRIMARY_KEY => 'id',
        Schema::COLUMNS => [
            'waitTime' => 'proprety_wait_time',
            'guarantee' => 'proprety_guarantee',
            'reCheck' => 'proprety_re_check',
            'bagReCheck' => 'proprety_bag_re_check',
            'id' => 'id',
        ],
        Schema::TYPECAST => [
            'waitTime' => 'int',
            'guarantee' => 'bool',
            'reCheck' => 'bool',
            'bagReCheck' => 'bool',
            'id' => 'int',
        ],
        Schema::RELATIONS => [],
    ],
];
